<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PortalFeedbackItem;

class AccountsAdminQuestionsSeeder extends Seeder
{
    public function run(): void
    {
        $questions = [
            [
                'reference' => 'AA-Q1',
                'title'     => 'Incoming Invoices — who are "Others"?',
                'description' => 'In your Accounts Admin view you show two types of Incoming Invoice: "From Associates" (already built) and "From Others". Who sends these "other" invoices? For example — external suppliers, venues, equipment providers, other clinics? Can you give one or two real examples from your day-to-day work so we build the right thing?',
                'section'   => 'Accounts Admin',
                'priority'  => 'high',
            ],
            [
                'reference' => 'AA-Q2',
                'title'     => 'Outgoing Invoices — do associates create them, or does admin?',
                'description' => 'Your Accounts Admin diagram shows Outgoing Invoices as: "Generated by associates → Approved by director → Sent to funder". Does this mean associates should be able to log/create an invoice themselves inside the portal, and admin then approves it? Or does admin always create the invoice using the associate\'s session data? This changes who has access to the invoice creation screen.',
                'section'   => 'Accounts Admin',
                'priority'  => 'high',
            ],
            [
                'reference' => 'AA-Q3',
                'title'     => 'Master Log — view only, or do staff enter data into it?',
                'description' => 'Your Master Log shows: Patient → Cost estimation submitted → Approved funding (Phase 1) → Expenses (Date, Purpose, Amount paid) → Balance → Add Another Phase. Is this a summary view that the portal calculates automatically from invoices and funding cycles already entered elsewhere? Or does someone manually type the Expense entries directly into the Master Log? Also — is "Balance" = Approved Funding minus all Expenses paid for that phase?',
                'section'   => 'Accounts Admin',
                'priority'  => 'critical',
            ],
        ];

        foreach ($questions as $q) {
            // Skip if this reference already exists
            if (PortalFeedbackItem::where('reference', $q['reference'])->exists()) {
                continue;
            }

            PortalFeedbackItem::create([
                'type'         => 'question',
                'section'      => $q['section'],
                'reference'    => $q['reference'],
                'priority'     => $q['priority'],
                'title'        => $q['title'],
                'description'  => $q['description'],
                'raised_by'    => 'Developer',
                'samy_status'  => 'pending',
                'dev_status'   => 'not_started',
                'is_seeded'    => false,
            ]);
        }
    }
}
