@php $header = 'Edit VTA Invoice'; @endphp
<x-app-layout>
    <div class="max-w-3xl mx-auto">
        <form method="POST" action="{{ route('vta-invoices.update', $vtaInvoice) }}" class="space-y-6">
            @csrf @method('PUT')
            <div class="rounded-xl border border-gray-200 bg-white p-6 space-y-4">
                <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div><label class="text-xs font-medium text-gray-500 uppercase tracking-wider">Patient</label><select name="patient_id" required class="mt-1 block w-full rounded-md border border-gray-300 px-3 py-2 shadow-sm focus:border-[#0092b4] focus:outline-none focus:ring-1 focus:ring-[#0092b4]">@foreach($patients as $p)<option value="{{ $p->id }}" {{ old('patient_id', $vtaInvoice->patient_id) == $p->id ? 'selected' : '' }}>{{ $p->first_name }} {{ $p->last_name }}</option>@endforeach</select></div>
                    <div><label class="text-xs font-medium text-gray-500 uppercase tracking-wider">Funding Cycle</label><select name="funding_cycle_id" class="mt-1 block w-full rounded-md border border-gray-300 px-3 py-2 shadow-sm focus:border-[#0092b4] focus:outline-none focus:ring-1 focus:ring-[#0092b4]"><option value="">None</option>@foreach($fundingCycles as $fc)<option value="{{ $fc->id }}" {{ old('funding_cycle_id', $vtaInvoice->funding_cycle_id) == $fc->id ? 'selected' : '' }}>Cycle {{ $fc->cycle_number }}</option>@endforeach</select></div>
                    <div><label class="text-xs font-medium text-gray-500 uppercase tracking-wider">Invoice Date</label><input type="date" name="invoice_date" value="{{ old('invoice_date', $vtaInvoice->invoice_date?->format('Y-m-d')) }}" class="mt-1 block w-full rounded-md border border-gray-300 px-3 py-2 shadow-sm focus:border-[#0092b4] focus:outline-none focus:ring-1 focus:ring-[#0092b4]"></div>
                    <div><label class="text-xs font-medium text-gray-500 uppercase tracking-wider">Due Date</label><input type="date" name="due_date" value="{{ old('due_date', $vtaInvoice->due_date?->format('Y-m-d')) }}" class="mt-1 block w-full rounded-md border border-gray-300 px-3 py-2 shadow-sm focus:border-[#0092b4] focus:outline-none focus:ring-1 focus:ring-[#0092b4]"></div>
                    <div><label class="text-xs font-medium text-gray-500 uppercase tracking-wider">Recipient Type</label><select name="recipient_type" required class="mt-1 block w-full rounded-md border border-gray-300 px-3 py-2 shadow-sm focus:border-[#0092b4] focus:outline-none focus:ring-1 focus:ring-[#0092b4]"><option value="Case Manager Company" {{ old('recipient_type', $vtaInvoice->recipient_type) == 'Case Manager Company' ? 'selected' : '' }}>Case Manager Company</option><option value="Solicitor" {{ old('recipient_type', $vtaInvoice->recipient_type) == 'Solicitor' ? 'selected' : '' }}>Solicitor</option><option value="Insurance Company" {{ old('recipient_type', $vtaInvoice->recipient_type) == 'Insurance Company' ? 'selected' : '' }}>Insurance Company</option><option value="Other" {{ old('recipient_type', $vtaInvoice->recipient_type) == 'Other' ? 'selected' : '' }}>Other</option></select></div>
                    <div><label class="text-xs font-medium text-gray-500 uppercase tracking-wider">Recipient Name</label><input type="text" name="recipient_name" value="{{ old('recipient_name', $vtaInvoice->recipient_name) }}" required class="mt-1 block w-full rounded-md border border-gray-300 px-3 py-2 shadow-sm focus:border-[#0092b4] focus:outline-none focus:ring-1 focus:ring-[#0092b4]"></div>
                    <div><label class="text-xs font-medium text-gray-500 uppercase tracking-wider">Recipient Email</label><input type="email" name="recipient_email" value="{{ old('recipient_email', $vtaInvoice->recipient_email) }}" class="mt-1 block w-full rounded-md border border-gray-300 px-3 py-2 shadow-sm focus:border-[#0092b4] focus:outline-none focus:ring-1 focus:ring-[#0092b4]"></div>
                    <div class="md:col-span-2"><label class="text-xs font-medium text-gray-500 uppercase tracking-wider">Address</label><textarea name="recipient_address" rows="2" class="mt-1 block w-full rounded-md border border-gray-300 px-3 py-2 shadow-sm focus:border-[#0092b4] focus:outline-none focus:ring-1 focus:ring-[#0092b4]">{{ old('recipient_address', $vtaInvoice->recipient_address) }}</textarea></div>
                    <div><label class="text-xs font-medium text-gray-500 uppercase tracking-wider">Sessions Invoiced</label><input type="number" name="sessions_invoiced" value="{{ old('sessions_invoiced', $vtaInvoice->sessions_invoiced) }}" min="0" class="mt-1 block w-full rounded-md border border-gray-300 px-3 py-2 shadow-sm focus:border-[#0092b4] focus:outline-none focus:ring-1 focus:ring-[#0092b4]"></div>
                    <div><label class="text-xs font-medium text-gray-500 uppercase tracking-wider">Session Amount</label><input type="number" name="session_amount" value="{{ old('session_amount', $vtaInvoice->session_amount) }}" step="0.01" min="0" class="mt-1 block w-full rounded-md border border-gray-300 px-3 py-2 shadow-sm focus:border-[#0092b4] focus:outline-none focus:ring-1 focus:ring-[#0092b4]"></div>
                    <div><label class="text-xs font-medium text-gray-500 uppercase tracking-wider">Additional Charges</label><input type="number" name="additional_charges" value="{{ old('additional_charges', $vtaInvoice->additional_charges) }}" step="0.01" min="0" class="mt-1 block w-full rounded-md border border-gray-300 px-3 py-2 shadow-sm focus:border-[#0092b4] focus:outline-none focus:ring-1 focus:ring-[#0092b4]"></div>
                    <div><label class="text-xs font-medium text-gray-500 uppercase tracking-wider">Total Amount</label><input type="number" name="total_amount" value="{{ old('total_amount', $vtaInvoice->total_amount) }}" step="0.01" min="0" required class="mt-1 block w-full rounded-md border border-gray-300 px-3 py-2 shadow-sm focus:border-[#0092b4] focus:outline-none focus:ring-1 focus:ring-[#0092b4]"></div>
                    <div><label class="text-xs font-medium text-gray-500 uppercase tracking-wider">Status</label><select name="status" class="mt-1 block w-full rounded-md border border-gray-300 px-3 py-2 shadow-sm focus:border-[#0092b4] focus:outline-none focus:ring-1 focus:ring-[#0092b4]"><option value="Draft" {{ old('status', $vtaInvoice->status) == 'Draft' ? 'selected' : '' }}>Draft</option><option value="Sent" {{ old('status', $vtaInvoice->status) == 'Sent' ? 'selected' : '' }}>Sent</option><option value="Paid" {{ old('status', $vtaInvoice->status) == 'Paid' ? 'selected' : '' }}>Paid</option><option value="Overdue" {{ old('status', $vtaInvoice->status) == 'Overdue' ? 'selected' : '' }}>Overdue</option><option value="Cancelled" {{ old('status', $vtaInvoice->status) == 'Cancelled' ? 'selected' : '' }}>Cancelled</option></select></div>
                    <div><label class="text-xs font-medium text-gray-500 uppercase tracking-wider">Payment Date</label><input type="date" name="payment_date" value="{{ old('payment_date', $vtaInvoice->payment_date?->format('Y-m-d')) }}" class="mt-1 block w-full rounded-md border border-gray-300 px-3 py-2 shadow-sm focus:border-[#0092b4] focus:outline-none focus:ring-1 focus:ring-[#0092b4]"></div>
                </div>
                <div><label class="text-xs font-medium text-gray-500 uppercase tracking-wider">Notes</label><textarea name="notes" rows="3" class="mt-1 block w-full rounded-md border border-gray-300 px-3 py-2 shadow-sm focus:border-[#0092b4] focus:outline-none focus:ring-1 focus:ring-[#0092b4]">{{ old('notes', $vtaInvoice->notes) }}</textarea></div>
            </div>
            <div class="flex items-center justify-end gap-3">
                <a href="{{ route('vta-invoices.show', $vtaInvoice) }}" class="rounded-lg border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50">Cancel</a>
                <button type="submit" class="rounded-lg bg-[#0092b4] px-6 py-2 text-sm font-medium text-white hover:bg-[#007a9a]"><i class="fa-solid fa-floppy-disk mr-1"></i> Update</button>
            </div>
        </form>
    </div>
</x-app-layout>
